### ISSUE TITLE
Markbot - index.html not online

### ISSUE THREAD

**Issue by char1129** [char1129/components-on-a-grid#1]
Hello @hellachella and @jessjodoin

I have completed the Components on a Grid html/css, but I keep on receiving an error saying my index.html file isn't online. I also have no idea what it wants for the header.
(I have pushed my edits to Github after same issue remains.)

I'll wait until the issues are resolved until I post a vocal solutions part to Github, to complete the assignment.

Help, please. 😊
@char1129 

<img width="1043" alt="Screen Shot 2020-09-12 at 4 45 11 PM" src="https://user-images.githubusercontent.com/55107755/93004693-5a85ea00-f517-11ea-9a63-330805fc233f.png">

**Comment by JessJodoin** [comment]
In your css, the header should be `display: contents; ` so that all the elements on the inside are able to be included in the grid

when you click the link under the 'not online' issue does it lead to the right repository?

**Comment by char1129** [comment]
> In your css, the header should be `display: contents; ` so that all the elements on the inside are able to be included in the grid
> 
> when you click the link under the 'not online' issue does it lead to the right repository?

Thank you. Now I have to reorganize my css!
It gives me a link that doesnt lead to my repository but when I check the fork, it says I did so already and the forked address is the same. See attached images... What do you think?

<img width="500" alt="Screen Shot 2020-09-12 at 8 29 43 PM" src="https://user-images.githubusercontent.com/55107755/93007410-d3e10500-f536-11ea-87aa-9f1fbcf9c0fa.png">
<img width="717" alt="Screen Shot 2020-09-12 at 8 29 51 PM" src="https://user-images.githubusercontent.com/55107755/93007411-d4799b80-f536-11ea-8102-067a27e8aba1.png">
<img width="1455" alt="Screen Shot 2020-09-12 at 8 30 05 PM" src="https://user-images.githubusercontent.com/55107755/93007413-d5123200-f536-11ea-8724-3c8aa002b5fb.png">

**Comment by JessJodoin** [comment]
I'm not sure if this will work but it might. In the markbot.yml file, at the top where it says `repo: "components-on-a-grid"` try rewriting 'components-on-a-grid', save and commit, and run it through markbot again. If that doesn't work we'll troubleshoot some more 😄

**Comment by JessJodoin** [comment]
Actually scratch that, it's not gunna do anything lol

**Comment by JessJodoin** [comment]
I also get this issue when I throw mine into markbot. I think it might be the repository itself cause it's the only one I've had this issue with. I've bugged Thomas so we'll see what he says 😄

**Comment by char1129** [comment]
> I also get this issue when I throw mine into markbot. I think it might be the repository itself cause it's the only one I've had this issue with. I've bugged Thomas so we'll see what he says 😄

I really appreciate you looking at my issue (especially during the weekend!!!!) I'll await Mastermind Thomas's answer as well 😊 Enjoy the rest of your weekend!!
![yup](https://user-images.githubusercontent.com/55107755/93008237-7ce02d80-f540-11ea-82b1-84e68e86fe25.jpg)

**Comment by char1129** [comment]
Fixed everything after making the header - display: content. 2% difference. I just have to wait to see why it doesn't seem to be online. 
<img width="1676" alt="Screen Shot 2020-09-13 at 2 28 27 AM" src="https://user-images.githubusercontent.com/55107755/93011909-0b68a500-f569-11ea-8202-bfd97b110d29.png">

**Comment by JessJodoin** [comment]
Hey @char1129 I've got the fix for the Markbot issue. Thomas said it was an issue with it not being set up for hosting.

Go to your repository on GitHub and look under 'settings'.
Scroll down to 'GitHub Pages' and enable them on your master branch.

<img width="927" alt="Screen Shot 2020-09-14 at 9 46 52 AM" src="https://user-images.githubusercontent.com/43217543/93094103-79978f80-f66f-11ea-971a-6258a1470a73.png">

Then on the GitHub desktop app, on that repository, click 'fetch origin'. And it should just load the changes. Throw it into Markbot and submit 😃

**Comment by char1129** [comment]
> Hey @char1129 I've got the fix for the Markbot issue. Thomas said it was an issue with it not being set up for hosting.
> 
> Go to your repository on GitHub and look under 'settings'.
> Scroll down to 'GitHub Pages' and enable them on your master branch.
> 
> <img alt="Screen Shot 2020-09-14 at 9 46 52 AM" width="927" src="https://user-images.githubusercontent.com/43217543/93094103-79978f80-f66f-11ea-971a-6258a1470a73.png">
> 
> Then on the GitHub desktop app, on that repository, click 'fetch origin'. And it should just load the changes. Throw it into Markbot and submit 😃

OMG YAY! It worked! Thank you so much!  
![yesNod](https://user-images.githubusercontent.com/55107755/93098782-3e985a80-f675-11ea-8263-5cffe3b8f648.gif)

**Comment by hellachella** [comment]
@JessJodoin Awesome. Please post this info in the main channel.
